defaults = dict(
    default=dict(
        rc={
            'figure.figsize': (10, 6),
            'axes.facecolor': '#ffffff',
            'figure.facecolor': '#ffffff',
            'grid.color': '#dddddd',
            'grid.linewidth': 0.5,
            'lines.linewidth': 1.5,
            'text.color': '#333333',
            'xtick.color': '#666666',
            'ytick.color': '#666666',
        },
        table_cmap='RdYlGn',
        colors={
            'benchmark': '#fedd78',
            'returns': '#348dc1',
            'drawdown': '#af4b64',
            'extra_0': '#4fa487',
            'extra_1': '#9b59b6',
            'extra_2': '#808080',
        },
        histogram_colors=dict(
            bar_color='#348dc1',
            kde_color='#003366',
            avg_color='#ff0000',
        ),
        table_colors=dict(
            outer_edge='#000000',
            inner_edge='#dddddd',
            face='#000000',
        ),
        cell_color='#ffffff',
        highlight_color='#ff0000',
        hlinecolor='#ff0000',
        hlinecolor_0='#000000',
        facecolor='#ffffff',
        title_text_color='#000000',
        subtitle_text_color='#808080',
        alpha=0.8,
        ts_alpha=1,
    ),
    grayscale=dict(
        rc={
            'figure.figsize': (10, 6),
            'axes.facecolor': '#ffffff',
            'figure.facecolor': '#ffffff',
            'grid.color': '#dddddd',
            'grid.linewidth': 0.5,
            'lines.linewidth': 1.5,
            'text.color': '#333333',
            'xtick.color': '#666666',
            'ytick.color': '#666666',
        },
        table_cmap='gray',
        colors={
            'benchmark': '#c0c0c0',
            'returns': '#222222',
            'drawdown': '#808080',
            'extra_0': '#c0c0c0',
            'extra_1': '#222222',
            'extra_2': '#808080',
        },
        histogram_colors=dict(
            bar_color='#c0c0c0',
            kde_color='#808080',
            avg_color='#000000',
        ),
        table_colors=dict(
            outer_edge='#000000',
            inner_edge='#dddddd',
            face='#000000',
        ),
        cell_color='#ffffff',
        highlight_color='#000000',
        hlinecolor='#808080',
        hlinecolor_0='#000000',
        facecolor='#ffffff',
        title_text_color='#000000',
        subtitle_text_color='#808080',
        alpha=0.5,
        ts_alpha=0.25,
    ),
)
